configserver:
    name: JHipster Registry config server
    status: Connected to the JHipster Registry config server, using Git's gitlabs
jhipster:
    security:
        authentication:
            jwt:
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
